#!/bin/bash

# Expects CLUSTER, SCRATCH from cluster-local cluster_env.sh (not in git).
repo_dir="$(dirname "$(realpath "$0")")"
source "$repo_dir/cluster_env.sh"

export ENROOT_CACHE_PATH=/tmp

docker_image=nvidia/pytorch:26.08-py3
enroot_image=${docker_image//[\/:]/+}

enroot load docker://nvcr.io/${docker_image}

set -ex

enroot start -r --rw \
    --mount /home/guangyunh:/home/guangyunh \
    --mount "$SCRATCH:/workspace" \
    --mount "$SCRATCH:$SCRATCH" \
    --mount "$repo_dir:/workspace/devenv" \
    "${enroot_image}" \
    bash -c -i 'cd /workspace/devenv && exec fish -i'
    # bash -c 'cd /workspace/devenv && exec fish -i'


